const METRIC_ENDPOINT = 'https://fake--endpoint.com/metrics';
const FEEDBACK_ENDPOINT = 'https://fake--endpoint.com/feedback';
const FEEDBACK_COMMENT_FIELD_SELECTOR = '#comment-field';
const FEEDBACK_MESSAGES_CONTAINER_SELECTOR = '#messages';
const FEEDBACK_SUBMIT_BUTTON_SELECTOR = '#submit';

export {
  METRIC_ENDPOINT,
  FEEDBACK_ENDPOINT,
  FEEDBACK_COMMENT_FIELD_SELECTOR,
  FEEDBACK_MESSAGES_CONTAINER_SELECTOR,
  FEEDBACK_SUBMIT_BUTTON_SELECTOR,
};
